version: 2.1

# Define reusable orbs
orbs:
  flutter: circleci/flutter@1.0.0

# Define jobs
jobs:
  test:
    executor: flutter/flutter
    steps:
      - checkout
      - flutter/install
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Run tests
          command: flutter test
      - run:
          name: Analyze code
          command: flutter analyze

  build-android:
    executor: flutter/flutter
    steps:
      - checkout
      - flutter/install
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Build APK (Debug)
          command: flutter build apk --debug
      - run:
          name: Build APK (Release)
          command: flutter build apk --release
      - run:
          name: Build App Bundle (Release)
          command: flutter build appbundle --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/
          destination: apk
      - store_artifacts:
          path: build/app/outputs/bundle/release/
          destination: appbundle

  build-android-signed:
    executor: flutter/flutter
    steps:
      - checkout
      - flutter/install
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Setup keystore (if available)
          command: |
            if [ -n "$KEYSTORE" ]; then
              echo "Setting up keystore for signed build..."
              echo $KEYSTORE | base64 --decode > android/app/keystore.jks
              echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
              echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
              echo "keyAlias=$KEY_ALIAS" >> android/key.properties
              echo "storeFile=keystore.jks" >> android/key.properties
            else
              echo "No keystore provided, building unsigned release..."
            fi
      - run:
          name: Build signed APK
          command: flutter build apk --release
      - run:
          name: Build signed App Bundle
          command: flutter build appbundle --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/
          destination: signed-apk
      - store_artifacts:
          path: build/app/outputs/bundle/release/
          destination: signed-appbundle

# Define workflows
workflows:
  test-and-build:
    jobs:
      - test
      - build-android:
          requires:
            - test
      - build-android-signed:
          requires:
            - test
          filters:
            branches:
              only: main

# Environment variables (set these in CircleCI project settings)
# KEYSTORE: Base64 encoded keystore file
# KEYSTORE_PASSWORD: Keystore password
# KEY_PASSWORD: Key password  
# KEY_ALIAS: Key alias
