version: 2.1

# Define jobs
jobs:
  test:
    docker:
      - image: cimg/android:2023.12.1
    steps:
      - checkout
      - run:
          name: Install Flutter
          command: |
            cd /home/circleci
            wget -O flutter_linux_3.16.0-stable.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.0-stable.tar.xz
            tar xf flutter_linux_3.16.0-stable.tar.xz
            echo 'export PATH="$PATH:/home/circleci/flutter/bin"' >> $BASH_ENV
      - run:
          name: Flutter doctor
          command: |
            source $BASH_ENV
            flutter doctor
      - run:
          name: Install dependencies
          command: |
            source $BASH_ENV
            flutter pub get
      - run:
          name: Run tests
          command: |
            source $BASH_ENV
            flutter test
      - run:
          name: Analyze code
          command: |
            source $BASH_ENV
            flutter analyze

  build-android:
    docker:
      - image: cimg/android:2023.12.1
    steps:
      - checkout
      - run:
          name: Install Flutter
          command: |
            cd /home/circleci
            wget -O flutter_linux_3.16.0-stable.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.0-stable.tar.xz
            tar xf flutter_linux_3.16.0-stable.tar.xz
            echo 'export PATH="$PATH:/home/circleci/flutter/bin"' >> $BASH_ENV
      - run:
          name: Flutter doctor
          command: |
            source $BASH_ENV
            flutter doctor
      - run:
          name: Install dependencies
          command: |
            source $BASH_ENV
            flutter pub get
      - run:
          name: Build APK (Debug)
          command: |
            source $BASH_ENV
            flutter build apk --debug
      - run:
          name: Build APK (Release)
          command: |
            source $BASH_ENV
            flutter build apk --release
      - run:
          name: Build App Bundle (Release)
          command: |
            source $BASH_ENV
            flutter build appbundle --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/
          destination: apk
      - store_artifacts:
          path: build/app/outputs/bundle/release/
          destination: appbundle

  build-android-signed:
    docker:
      - image: cimg/android:2023.12.1
    steps:
      - checkout
      - run:
          name: Install Flutter
          command: |
            cd /home/circleci
            wget -O flutter_linux_3.16.0-stable.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.0-stable.tar.xz
            tar xf flutter_linux_3.16.0-stable.tar.xz
            echo 'export PATH="$PATH:/home/circleci/flutter/bin"' >> $BASH_ENV
      - run:
          name: Flutter doctor
          command: |
            source $BASH_ENV
            flutter doctor
      - run:
          name: Install dependencies
          command: |
            source $BASH_ENV
            flutter pub get
      - run:
          name: Setup keystore (if available)
          command: |
            if [ -n "$KEYSTORE" ]; then
              echo "Setting up keystore for signed build..."
              echo $KEYSTORE | base64 --decode > android/app/keystore.jks
              echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
              echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
              echo "keyAlias=$KEY_ALIAS" >> android/key.properties
              echo "storeFile=keystore.jks" >> android/key.properties
            else
              echo "No keystore provided, building unsigned release..."
            fi
      - run:
          name: Build signed APK
          command: |
            source $BASH_ENV
            flutter build apk --release
      - run:
          name: Build signed App Bundle
          command: |
            source $BASH_ENV
            flutter build appbundle --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/
          destination: signed-apk
      - store_artifacts:
          path: build/app/outputs/bundle/release/
          destination: signed-appbundle

# Define workflows
workflows:
  test-and-build:
    jobs:
      - test
      - build-android:
          requires:
            - test
      - build-android-signed:
          requires:
            - test
          filters:
            branches:
              only: main

# Environment variables (set these in CircleCI project settings)
# KEYSTORE: Base64 encoded keystore file
# KEYSTORE_PASSWORD: Keystore password
# KEY_PASSWORD: Key password  
# KEY_ALIAS: Key alias
